# Generated by Django 4.1.2 on 2022-10-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_de_muerte', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32)),
                ('sumario', models.TextField(help_text='Pon aqui de que va el libro', max_length=100)),
                ('isbn', models.CharField(help_text='Isbn maximo de 13 caracteres', max_length=13, verbose_name='ISBN')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.autor')),
                ('genero', models.ManyToManyField(to='catalog.genero')),
            ],
        ),
    ]
